# Horizon Points
# This Message is published by Horizon Plotter

# left horizon point in image 2D
geometry_msgs/Vector3 pt_left

# right horizon point in image 2D
geometry_msgs/Vector3 pt_right

# center horizon point in image 2D
geometry_msgs/Vector3 pt_center

# center max depth point in image 2D
geometry_msgs/Vector3 pt_max_depth

# center min depth point in image 2D
geometry_msgs/Vector3 pt_min_depth_left

# center min depth point in image 2D
geometry_msgs/Vector3 pt_min_depth_right

# center min depth inbetween point in image 2D
geometry_msgs/Vector3 pt_min_depth_ib

