# Target
# This Message is published by Horizon Plotter

Header header

# Target Y [m]
float64 Y

# Target depth [m]
float64 depth

# Target side [1 left; 0 center; 1 right]
float64 side

# Target valid [true; false]
bool valid

# Obstacle depth [m]
float64 obstacle_depth

# Target valid [true; false]
float64 obstacle_Y

# Drone yaw when image taken [rad]
float64 yaw

# Drone position when image taken [m]
geometry_msgs/Vector3 position


